#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

DESTDIR = Debug
CONFIG += debug

DEFINES += 
LIBS += 
INCLUDEPATH += ../../../../../../SysGCC/beaglebone/arm-linux-gnueabihf/sysroot/usr/include/arm-linux-gnueabihf/qt5/QtCharts
QMAKE_LFLAGS += 
QMAKE_CXXFLAGS += -ggdb 
QMAKE_CFLAGS += -ggdb 
